# --------------------------------------------------------------
#
#   This file is part of voyage.
#    __file__ : DockerFile
#   __author__ = 'Sri Pandi, Satheesh Rathinakumar'
#
# --------------------------------------------------------------


FROM nginx:1.15.2

RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/

