# --------------------------------------------------------------
#
#   This file is part of voyage.
#    __file__ : DockerFile
#   __author__ = 'Sri Pandi, Satheesh Rathinakumar'
#
# --------------------------------------------------------------

FROM postgres

# Removed - Not required.
# ADD create.sql /docker-entrypoint-initdb.d